export enum UsersTypes {
	SIGN_UP = 'SIGN_UP',
	SIGN_IN = 'SIGN_IN',
	GET_USER = 'GET_USER',
	LOGOUT = 'LOGOUT',
}

export enum IncomeTypes {
	CREATE_INCOME = 'CREATE_INCOME',
	LIST_INCOME = 'LIST_INCOME',
	UPDATE_INCOME = 'UPDATE_INCOME',
	DELETE_INCOME = 'DELETE_INCOME',
}
export enum ExpensesTypes {
	CREATE_EXPENSES = 'CREATE_EXPENSES',
	LIST_EXPENSES = 'LIST_EXPENSES',
	UPDATE_EXPENSES = 'UPDATE_EXPENSES',
	DELETE_EXPENSES = 'DELETE_EXPENSES',
}
